<?php
// Include the API methods
require_once('jquery_ui_dialog.api.inc');
// $Id$

# Copyright (c) 2010 Impressive.media
# Author: Eugen Mayer
/*
 * This helper makes it possible to force dialog iframe, so the child call,
 * to use a different page.tpl.php, which does not include all thos regions, headers
 * But only the css / js files and a clean layout (no layout)
 */
function jquery_ui_dialog_theme_registry_alter(&$theme_registry) {
  if (isset($theme_registry['page']) && isset($theme_registry['page']['theme paths'])) {
    $module_path = drupal_get_path('module', 'jquery_ui_dialog');
    array_unshift($theme_registry['page']['theme paths'], $module_path);
    array_unshift($theme_registry['page']['preprocess functions'], 'jquery_ui_dialog_pre_preprocess_page');
  }
}

/**
 * Preprocess template variables for page.tpl.php - step 1.
 *
 * Performance enhancement: prevent template_preprocess_page() from generating
 * sidebar blocks when a modal frame has been requested.
 */
function jquery_ui_dialog_pre_preprocess_page(&$variables) {
  if (!empty($GLOBALS['jquery_ui_dialog_page_template'])) {
    $variables['show_blocks'] = FALSE;
  }
}

/**
 * Preprocess template variables for page.tpl.php - step 2.
 *
 * Now that we have altered the registry entry for theme('page'), we can tell
 * theme() to use a different template file name when we need to render a child
 * window.
 */
function jquery_ui_dialog_preprocess_page(&$variables) {
  if (!empty($GLOBALS['jquery_ui_dialog_page_template'])) {
    if (!isset($variables['template_files'])) {
      $variables['template_files'] = array();
    }
    array_unshift($variables['template_files'], 'jquery_ui_dialog-page');
  }
}